export const permissionRegistry = [
  { code: "users.view", module: "users", description: "View users" },
  { code: "users.create", module: "users", description: "Create users" },
  { code: "users.update", module: "users", description: "Update users" },
  { code: "platform.admin", module: "platform", description: "Administer platform configuration — AI providers, notifications, email, integrations" },
  { code: "finance.view", module: "finance", description: "View contracts, variations, and progress claims" },
  { code: "finance.manage", module: "finance", description: "Create and manage contracts, variations, and progress claims" },
  { code: "finance.admin", module: "finance", description: "Approve progress claims, record payments, edit contract values" },
  { code: "roles.view", module: "roles", description: "View roles" },
  { code: "roles.create", module: "roles", description: "Create roles" },
  { code: "roles.update", module: "roles", description: "Update roles" },
  { code: "permissions.view", module: "permissions", description: "View permissions" },
  { code: "audit.view", module: "audit", description: "View audit logs" },
  { code: "sharepoint.view", module: "platform", description: "View SharePoint platform configuration" },
  { code: "sharepoint.manage", module: "platform", description: "Manage SharePoint-linked folders and files" },
  { code: "notifications.view", module: "platform", description: "View notifications" },
  { code: "notifications.manage", module: "platform", description: "Manage notification status" },
  { code: "search.view", module: "platform", description: "Use platform search" },
  { code: "dashboards.view", module: "platform", description: "View dashboards" },
  { code: "dashboards.manage", module: "platform", description: "Create and edit dashboards" },
  { code: "masterdata.view", module: "masterdata", description: "View master data records" },
  { code: "masterdata.manage", module: "masterdata", description: "Create and update master data records" },
  { code: "resources.view", module: "resources", description: "View worker availability, competencies, and suitability" },
  { code: "resources.manage", module: "resources", description: "Manage worker availability, competencies, and suitability" },
  { code: "assets.view", module: "assets", description: "View asset register and assignment visibility" },
  { code: "assets.manage", module: "assets", description: "Manage asset register and categories" },
  { code: "maintenance.view", module: "maintenance", description: "View maintenance plans, events, inspections, and breakdowns" },
  { code: "maintenance.manage", module: "maintenance", description: "Manage maintenance plans, events, inspections, and breakdowns" },
  { code: "forms.view", module: "forms", description: "View form templates and submissions" },
  { code: "forms.submit", module: "forms", description: "Submit forms — fill and lodge submissions" },
  { code: "forms.manage", module: "forms", description: "Create and edit form templates" },
  { code: "forms.approve", module: "forms", description: "Approve or reject form submissions in approval chains" },
  { code: "forms.admin", module: "forms", description: "Delete templates, view all submissions, manage schedules" },
  { code: "documents.view", module: "documents", description: "View SharePoint-backed document records and filtered document lists" },
  { code: "documents.manage", module: "documents", description: "Create document links, versions, and document access rules" },
  { code: "tenders.view", module: "tendering", description: "View tenders" },
  { code: "tenders.manage", module: "tendering", description: "Create and update tenders" },
  { code: "tenderdocuments.view", module: "tendering", description: "View tender documents" },
  { code: "tenderdocuments.manage", module: "tendering", description: "Manage tender documents" },
  { code: "jobs.view", module: "jobs", description: "View jobs" },
  { code: "jobs.manage", module: "jobs", description: "Create and manage jobs" },
  { code: "scheduler.view", module: "scheduler", description: "View scheduler workspace" },
  { code: "scheduler.manage", module: "scheduler", description: "Create shifts and manage assignments" },
  { code: "tenderconversion.manage", module: "tendering", description: "Award tenders, issue contracts, and convert tenders to jobs" },
  { code: "estimates.view", module: "tendering", description: "View tender estimates and rate library" },
  { code: "estimates.manage", module: "tendering", description: "Create and update tender estimates" },
  { code: "estimates.admin", module: "tendering", description: "Manage rate library and estimate configuration" },
  { code: "projects.view", module: "projects", description: "View projects, scope, team, and activity log" },
  { code: "projects.manage", module: "projects", description: "Update project team, status, budget, milestones, documents" },
  { code: "projects.admin", module: "projects", description: "Create projects manually, change contract value, reopen closed projects" },
  { code: "field.view", module: "field", description: "Access the field worker app — own allocations, pre-starts, timesheets, documents" },
  { code: "field.manage", module: "field", description: "Approve timesheets and view all field submissions (PM / WHS / Admin)" },
  { code: "directory.view", module: "directory", description: "View business directory — clients, subcontractors, suppliers" },
  { code: "directory.manage", module: "directory", description: "Create and update directory entries, contacts, licences, insurances" },
  { code: "directory.admin", module: "directory", description: "Delete directory entries, approve credit, update prequalification status" },
  { code: "directory.finance", module: "directory", description: "View and edit bank details on directory entries" },
  { code: "compliance.view", module: "compliance", description: "View compliance records and expiry alerts" },
  { code: "compliance.manage", module: "compliance", description: "Add and edit licences, insurance, qualifications" },
  { code: "compliance.admin", module: "compliance", description: "Override compliance blocks, send manual alerts" },
  { code: "safety.view", module: "safety", description: "View safety incidents and hazard observations" },
  { code: "safety.manage", module: "safety", description: "Report and update incidents and hazard observations" },
  { code: "safety.admin", module: "safety", description: "Close incidents/hazards, manage corrective actions" },
  { code: "portal.invite", module: "portal", description: "Invite client contacts to the client portal" }
] as const;
