export const permissionRegistry = [
  { code: "users.view", module: "users", description: "View users" },
  { code: "users.create", module: "users", description: "Create users" },
  { code: "users.update", module: "users", description: "Update users" },
  { code: "platform.admin", module: "platform", description: "Administer platform configuration — AI providers, notifications, email, integrations" },
  { code: "finance.view", module: "finance", description: "View contracts, variations, and progress claims" },
  { code: "finance.manage", module: "finance", description: "Create and manage contracts, variations, and progress claims" },
  { code: "finance.admin", module: "finance", description: "Approve progress claims, record payments, edit contract values" },
  { code: "roles.view", module: "roles", description: "View roles" },
  { code: "roles.create", module: "roles", description: "Create roles" },
  { code: "roles.update", module: "roles", description: "Update roles" },
  { code: "permissions.view", module: "permissions", description: "View permissions" },
  { code: "audit.view", module: "audit", description: "View audit logs" },
  { code: "sharepoint.view", module: "platform", description: "View SharePoint platform configuration" },
  { code: "sharepoint.manage", module: "platform", description: "Manage SharePoint-linked folders and files" },
  { code: "notifications.view", module: "platform", description: "View notifications" },
  { code: "notifications.manage", module: "platform", description: "Manage notification status" },
  { code: "search.view", module: "platform", description: "Use platform search" },
  { code: "dashboards.view", module: "platform", description: "View dashboards" },
  { code: "dashboards.manage", module: "platform", description: "Create and edit dashboards" },
  { code: "masterdata.view", module: "masterdata", description: "View master data records" },
  { code: "masterdata.manage", module: "masterdata", description: "Create and update master data records" },
  { code: "resources.view", module: "resources", description: "View worker availability, competencies, and suitability" },
  { code: "resources.manage", module: "resources", description: "Manage worker availability, competencies, and suitability" },
  { code: "assets.view", module: "assets", description: "View asset register and assignment visibility" },
  { code: "assets.manage", module: "assets", description: "Manage asset register and categories" },
  { code: "maintenance.view", module: "maintenance", description: "View maintenance plans, events, inspections, and breakdowns" },
  { code: "maintenance.manage", module: "maintenance", description: "Manage maintenance plans, events, inspections, and breakdowns" },
  { code: "inventory.view", module: "inventory", description: "View stock items and movements" },
  { code: "inventory.manage", module: "inventory", description: "Manage stock items, movements, and stocktakes" },
  { code: "forms.view", module: "forms", description: "View form templates and submissions" },
  { code: "forms.submit", module: "forms", description: "Submit forms — fill and lodge submissions" },
  { code: "forms.manage", module: "forms", description: "Create and edit form templates" },
  { code: "forms.approve", module: "forms", description: "Approve or reject form submissions in approval chains" },
  { code: "forms.admin", module: "forms", description: "Delete templates, view all submissions, manage schedules" }, // reserved — Forms Engine Phase 2; declared but not yet enforced (see audit 2026-05-02 finding m1)
  { code: "documents.view", module: "documents", description: "View SharePoint-backed document records and filtered document lists" },
  { code: "documents.manage", module: "documents", description: "Create document links, versions, and document access rules" },
  { code: "tenders.view", module: "tendering", description: "View tenders" },
  { code: "tenders.manage", module: "tendering", description: "Create and update tenders" },
  { code: "tenderdocuments.view", module: "tendering", description: "View tender documents" },
  { code: "tenderdocuments.manage", module: "tendering", description: "Manage tender documents" },
  { code: "jobs.view", module: "jobs", description: "View jobs" },
  { code: "jobs.manage", module: "jobs", description: "Create and manage jobs" },
  { code: "scheduler.view", module: "scheduler", description: "View scheduler workspace" },
  { code: "scheduler.manage", module: "scheduler", description: "Create shifts and manage assignments" },
  { code: "calendar.sync", module: "scheduler", description: "Sync schedulable items to the user's calendar (PR-216 mock-mode)" },
  { code: "tenderconversion.manage", module: "tendering", description: "Award tenders, issue contracts, and convert tenders to jobs" },
  { code: "estimates.view", module: "tendering", description: "View tender estimates and rate library" },
  { code: "estimates.manage", module: "tendering", description: "Create and update tender estimates" },
  { code: "estimates.admin", module: "tendering", description: "Manage rate library and estimate configuration" },
  { code: "projects.view", module: "projects", description: "View projects, scope, team, and activity log" },
  { code: "projects.manage", module: "projects", description: "Update project team, status, budget, milestones, documents" },
  { code: "projects.admin", module: "projects", description: "Create projects manually, change contract value, reopen closed projects" },
  { code: "field.view", module: "field", description: "Access the field worker app — own allocations, pre-starts, timesheets, documents" },
  { code: "field.manage", module: "field", description: "Approve timesheets and view all field submissions (PM / WHS / Admin)" },
  { code: "directory.view", module: "directory", description: "View business directory — clients, subcontractors, suppliers" },
  { code: "directory.manage", module: "directory", description: "Create and update directory entries, contacts, licences, insurances" },
  { code: "directory.admin", module: "directory", description: "Delete directory entries, approve credit, update prequalification status" },
  { code: "directory.finance", module: "directory", description: "View and edit bank details on directory entries" },
  { code: "compliance.view", module: "compliance", description: "View compliance records and expiry alerts" },
  { code: "compliance.manage", module: "compliance", description: "Add and edit licences, insurance, qualifications" },
  { code: "compliance.admin", module: "compliance", description: "Override compliance blocks, send manual alerts" },
  { code: "safety.view", module: "safety", description: "View safety incidents and hazard observations" },
  { code: "safety.manage", module: "safety", description: "Report and update incidents and hazard observations" },
  { code: "safety.admin", module: "safety", description: "Close incidents/hazards, manage corrective actions" },
  { code: "portal.invite", module: "portal", description: "Invite client contacts to the client portal" },
  { code: "ai.persona.tendering", module: "ai", description: "Use the Tendering Assistant AI persona — chat, settings, instruction overrides" },
  { code: "authority.manage", module: "authority", description: "Manage authority rules — configurable spend limits and approval thresholds" },
  // Rates & Lists R0 (PR-487). `rates.manage` gates flexible RateTable/Column/Row
  // authoring; `lists.manage` gates ListBinding CRUD (whole-list delete is
  // separately restricted — TODO: route through the authority seam once merged).
  { code: "rates.manage", module: "rates", description: "Create and edit flexible rate tables (RateTable / RateColumn / RateRow)" },
  { code: "lists.manage", module: "lists", description: "Manage list bindings and list-consumer wiring" },
  // Comms + Approvals Phase 2 slice 1 (PR ${TBD}). Decide/overrule route
  // through the AuthorityService seam + managerId reporting chain.
  { code: "approvals.view", module: "approvals", description: "View approval-decision history for a record" },
  { code: "approvals.decide", module: "approvals", description: "Record an approval decision (approve or reject) on a record" },
  { code: "approvals.overrule", module: "approvals", description: "Overrule a prior approval decision as a senior in the reporting chain" },
  { code: "internal-messages.view", module: "approvals", description: "View internal record-anchored messages you sent or received" },
  { code: "internal-messages.send", module: "approvals", description: "Send an internal record-anchored message to another user" },
  // Procurement (PR-488 slice 1). `view` gates lists and detail; `manage` gates
  // draft/edit/submit/cancel; `approve` is the target permission the authority
  // seam consults when routing an over-limit approval; `receive` gates posting
  // a receipt (which writes a RECEIVE StockMovement via the inventory layer).
  { code: "procurement.view", module: "procurement", description: "View procurement requests and purchase orders" },
  { code: "procurement.manage", module: "procurement", description: "Create, edit, submit, cancel procurement requests" },
  { code: "procurement.approve", module: "procurement", description: "Approve procurement requests and issue purchase orders" },
  { code: "procurement.receive", module: "procurement", description: "Record receipt of goods against a procurement line" }
] as const;
