// Pure diff and SQL-render utilities for role-grant migrations.
// No Prisma imports. No database writes. No side effects.

export interface GrantItem {
  role: string;
  code: string;
}

export interface GrantDiff {
  added: GrantItem[];
  removed: GrantItem[];
}

/**
 * Compute the symmetric diff between the in-code map and the on-disk lock.
 * Both `added` and `removed` are sorted by role then code.
 */
export function diffGrants(
  map: Readonly<Record<string, readonly string[]>>,
  lock: Readonly<Record<string, readonly string[]>>
): GrantDiff {
  const added: GrantItem[] = [];
  const removed: GrantItem[] = [];

  const allRoles = new Set([...Object.keys(map), ...Object.keys(lock)]);

  for (const role of allRoles) {
    const mapCodes = new Set(map[role] ?? []);
    const lockCodes = new Set(lock[role] ?? []);

    for (const code of mapCodes) {
      if (!lockCodes.has(code)) {
        added.push({ role, code });
      }
    }
    for (const code of lockCodes) {
      if (!mapCodes.has(code)) {
        removed.push({ role, code });
      }
    }
  }

  const sortFn = (a: GrantItem, b: GrantItem) =>
    a.role < b.role ? -1 : a.role > b.role ? 1 : a.code < b.code ? -1 : a.code > b.code ? 1 : 0;

  added.sort(sortFn);
  removed.sort(sortFn);

  return { added, removed };
}

/**
 * Convert a role name to a slug suitable for use in migration IDs.
 * Lower-case; any non-alphanumeric character becomes a hyphen.
 * Consecutive hyphens are collapsed; leading/trailing hyphens stripped.
 */
function toSlug(role: string): string {
  return role
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Render a DO $$ migration block that inserts the given grants insert-if-absent.
 * Matches the shape of 20260804120000_grant_field_worker_expenses/migration.sql.
 *
 * @param added       Grants to insert (must be non-empty).
 * @param timestampUtc ISO-8601 UTC timestamp string (used only in the header comment).
 */
export function renderGrantMigration(added: GrantItem[], timestampUtc: string): string {
  if (added.length === 0) {
    throw new Error("renderGrantMigration: added list is empty — nothing to render");
  }

  // Group by role for the reverse-documentation block.
  const byRole = new Map<string, string[]>();
  for (const { role, code } of added) {
    if (!byRole.has(role)) byRole.set(role, []);
    byRole.get(role)!.push(code);
  }

  const reverseLines: string[] = [];
  for (const [role, codes] of byRole) {
    const codeList = codes.map((c) => `'${c}'`).join(", ");
    reverseLines.push(
      `--   To reverse: remove the role_permissions rows for this role / code set.`,
      `--   Example (run manually, never in CI):`,
      `--     role: '${role}'`,
      `--     codes: ${codeList}`,
      `--   Use: WHERE role_id = (SELECT id FROM "roles" WHERE name = '${role}')`,
      `--     AND permission_id IN (SELECT id FROM "permissions" WHERE code IN (${codeList}))`
    );
  }

  const roleSlugsInvolved = [...byRole.keys()].map(toSlug).join(", ");

  const grantBlocks: string[] = [];
  for (const { role, code } of added) {
    const roleSlug = toSlug(role);
    const codeSlug = code.replace(/\./g, "-");
    const id = `rp-${roleSlug}-${codeSlug}`;
    grantBlocks.push(
      `  -- ${role} -> ${code}`,
      `  SELECT id INTO v_role_id FROM "roles" WHERE name = '${role}' LIMIT 1;`,
      `  IF v_role_id IS NULL THEN`,
      `    RAISE NOTICE 'role_grants: "${role}" role absent, skipping.';`,
      `  ELSE`,
      `    SELECT id INTO v_perm_id FROM "permissions" WHERE code = '${code}' LIMIT 1;`,
      `    IF v_perm_id IS NULL THEN`,
      `      RAISE NOTICE 'role_grants: permission ${code} absent, skipping.';`,
      `    ELSE`,
      `      INSERT INTO "role_permissions" (id, role_id, permission_id, assigned_at)`,
      `      VALUES ('${id}', v_role_id, v_perm_id, NOW())`,
      `      ON CONFLICT DO NOTHING;`,
      `    END IF;`,
      `  END IF;`,
      ``
    );
  }

  return [
    `-- Role-grant migration — generated by grants:write at ${timestampUtc}`,
    `-- Roles involved: ${roleSlugsInvolved}`,
    `--`,
    `-- Semantics: insert-if-absent only. Idempotent. Safe when the role or`,
    `-- permission is absent (fresh test DB). Never deletes or updates any row.`,
    `--`,
    `-- Reverse (run manually if rolling back):`,
    ...reverseLines,
    ``,
    `DO $$`,
    `DECLARE`,
    `  v_role_id TEXT;`,
    `  v_perm_id TEXT;`,
    `BEGIN`,
    ``,
    ...grantBlocks,
    `END $$;`,
    ``
  ].join("\n");
}
