import { Test } from "@nestjs/testing";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.js";
import { PdfRendererService } from "../pdf-renderer.service";
import { PdfRenderError } from "../pdf-render.error";

describe("PdfRendererService (integration)", () => {
  let service: PdfRendererService;

  beforeAll(async () => {
    const module = await Test.createTestingModule({
      providers: [PdfRendererService],
    }).compile();

    service = module.get(PdfRendererService);
  });

  afterAll(async () => {
    await service.onModuleDestroy();
  });

  it("renders the sample template to a valid PDF with at least 1 page", async () => {
    const buf = await service.renderTemplateToPdf("sample.html", {
      title: "Integration Test",
      date: "2026-05-25",
      footer: "Generated by automated test.",
    });

    expect(buf).toBeInstanceOf(Buffer);
    expect(buf.length).toBeGreaterThan(1000);
    expect(buf.subarray(0, 5).toString("ascii")).toBe("%PDF-");

    const doc = await pdfjsLib.getDocument({
      data: new Uint8Array(buf),
      useSystemFonts: true,
    }).promise;
    expect(doc.numPages).toBeGreaterThanOrEqual(1);
    doc.destroy();
  }, 60_000);

  it("renders with custom margins", async () => {
    const buf = await service.renderHtmlToPdf(
      "<html><body><p>Custom margins</p></body></html>",
      { margin: { top: "10mm", bottom: "10mm", left: "10mm", right: "10mm" } },
    );

    expect(buf.subarray(0, 5).toString("ascii")).toBe("%PDF-");
    expect(buf.length).toBeGreaterThan(500);
  }, 60_000);

  it("renders with header and footer enabled", async () => {
    const buf = await service.renderHtmlToPdf(
      "<html><body><p>Header/footer test</p></body></html>",
      {
        displayHeaderFooter: true,
        headerHtml: '<div style="font-size:8px;text-align:center;width:100%;">Test Header</div>',
        footerHtml: '<div style="font-size:8px;text-align:center;width:100%;">Page <span class="pageNumber"></span></div>',
      },
    );

    expect(buf.subarray(0, 5).toString("ascii")).toBe("%PDF-");
    expect(buf.length).toBeGreaterThan(500);
  }, 60_000);

  it("throws PdfRenderError for a missing template", async () => {
    await expect(
      service.renderTemplateToPdf("does-not-exist.html", {}),
    ).rejects.toThrow(PdfRenderError);
  });
});
