import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const d = dirname(fileURLToPath(import.meta.url));
const SRC = join(d, 'src'); if (!existsSync(SRC)) mkdirSync(SRC);
let html = readFileSync(join(d, 'viewer-template.html'), 'utf8');
const css = (html.match(/<style>([\s\S]*?)<\/style>/) || [])[1] || '';
writeFileSync(join(SRC, 'styles.css'), css.trim() + '\n');
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
const dataBlock = scripts.find(s => s[1].includes('__WORKFLOWS_JSON__'));
const appBlocks = scripts.filter(s => s !== dataBlock).map(s => s[1].trim());
writeFileSync(join(SRC, 'app.js'), appBlocks.join('\n\n') + '\n');
html = html.replace(/<style>[\s\S]*?<\/style>/, '<link rel="stylesheet" href="styles.css">');
html = html.replace(dataBlock[0], '<script src="workflows.js"></script>');
let first = true;
html = html.replace(/<script>[\s\S]*?<\/script>/g, () => { if (first) { first = false; return '<script src="app.js"></script>'; } return ''; });
html = html.replace(/\n{3,}/g, '\n\n');
writeFileSync(join(SRC, 'index.html'), html);
console.log('css bytes:', css.length, '| app blocks:', appBlocks.length, '| total scripts:', scripts.length);
